# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:

env:
  PROJECT_ID: my-page-jpro-test
  REGION: europe
  RECEIVER_IMAGE: europe-docker.pkg.dev/my-page-jpro-test/slack-cv-bot/slack-cv-bot-receiver
  HANDLER_IMAGE: europe-docker.pkg.dev/my-page-jpro-test/slack-cv-bot/slack-cv-bot-handler

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

  push:
    if: ${{ github.ref == 'refs/heads/main' && github.repository == 'jprofessionals/slack-cv-bot' }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: test

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{env.PROJECT_ID}}

      - name: Test gcloud CLI"
        run: gcloud info

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Jib
        run: ./gradlew build jibDockerBuild

      - name: Push receiver to docker
        run: docker push ${{ env.RECEIVER_IMAGE }}

      - name: Push handler to docker
        run: docker push ${{ env.HANDLER_IMAGE }}


  run-terraform-test:
    needs:
      - push
    runs-on: ubuntu-latest
    environment: test
    concurrency: terraform-lock-test

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3
      - run: terraform get
        working-directory: infrastructure
      - run: terraform init -backend-config="bucket=terraform-state-slack-cv-bot-my-page-jpro-test"
        working-directory: infrastructure
      - run: terraform apply -auto-approve -input=false -var-file=test.tfvars
        working-directory: infrastructure

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
